apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantuml
  # labels so that we can bind a Service to this Pod
  labels:
    app: plantuml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantuml
  template:
    metadata:
      labels:
        app: plantuml
    spec:
      containers:
      - name: plantuml
        image: plantuml/plantuml-server:tomcat
        livenessProbe:
          tcpSocket:
            port: 8080
        ports:
        - containerPort: 8080
